### ISSUE TITLE
[RFC] Use Role Based Security

### ISSUE THREAD

**Issue by j8r** [DFabric/dppm-rest-api#1]
Inspired by [HashiCorp Vault policies](https://www.vaultproject.io/docs/concepts/policies.html#policy-syntax).

This allows to finely manage API route access, using patterns and permission composition.
The default permission is to deny the access to the resource.

This implementation isn't optimized, we can cache the roles in to the user struct in the future.

In the future we can even allow/disallow parameters like `?host=` or `?port=`

```cr
require "json"

struct Document
  include JSON::Serializable
  getter groups : Array(Group)
  getter users : Array(User)

  struct User
    include JSON::Serializable
    getter name : String,
      id : String,
      group_ids : Set(String)
  end

  struct Group
    include JSON::Serializable
    getter name : String,
      id : String,
      description : String,
      path_policies : Hash(String, PathPolicy)

    def path_permissions(path : String, &block : Set(PathPolicy::Permission) ->)
      path_policies.each do |path_key, policy|
        if File.match? path_key, path
          yield policy.permissions
        end
      end
    end

    struct PathPolicy
      include JSON::Serializable
      getter permissions : Set(Permission)

      enum Permission
        Create
        Read
        Update
        Delete

        def self.new(permission : String)
          {% begin %}
          case permission
            {% for const in @type.constants %}
          when {{const.downcase}} then {{const}}
            {% end %}
          else raise "invalid permission: #{permission}"
          end
          {% end %}
        end

        def to_json(json : JSON::Builder)
          {% begin %}
          case self
            {% for const in @type.constants %}
          when {{const}} then json.string "{{const.downcase}}"
            {% end %}
          else raise "unkown permission: #{value}"
          end
          {% end %}
        end
      end
    end
  end

  def path_permissions(user : String, path : String) : Set(Group::PathPolicy::Permission)?
    puts path
    permissions = nil

    if user = @users.find &.name.== "Tom"
      @groups.each do |group|
        if user.group_ids.includes? group.id
          group.path_permissions path do |group_permissions|
            if permissions
              permissions = permissions & group_permissions
            else
              permissions = group_permissions
            end
          end
        end
      end
    end
    if !permissions || permissions.try &.empty?
      puts "access to `#{path}` denied to #{user}"
      return
    end
    puts permissions
  end
end

json = <<-JSON
{ "users" : [
    {
       "name": "Tom",
       "id": "092",
       "group_ids": ["123"]
    }
  ],
  "groups": [
     {
      "name": "User",
      "id": "123",
      "description": "Default user group",
      "path_policies": {
        "/**": {
          "permissions": ["create", "read", "update", "delete"]
        },
        "/app/**": {
          "permissions": ["read", "update"]
        },
        "/app/*-private": {
          "permissions": []
        },
        "/app/dppm": {
          "permissions": []
        }
      }
    }
  ]
}
JSON

doc = Document.from_json json

doc.path_permissions "Tom", "/app"
doc.path_permissions "Tom", "/app/dppm"
doc.path_permissions "Tom", "/app/new-app"
doc.path_permissions "Tom", "/app/new-private"

```
Output:
``` 
/app
Set{Create, Read, Update, Delete}
/app/dppm
access to `/app/dppm` denied to Document::User(@name="Tom", @id="092", @group_ids=Set{"123"})
/app/new-app
Set{Read, Update}
/app/new-private
access to `/app/new-private` denied to Document::User(@name="Tom", @id="092", @group_ids=Set{"123"})
```

**Comment by j8r** [comment]
Using IDs are more robust than names, I suggest also to rename `Role` to `Group` like https://cloudron.io/developer/api/#groups. I think the name is more user-friendly.

**Comment by dscottboggs** [comment]
having spent some time working on implementing this and studying the API, I have a few proposals:

 - The concept of ownership still makes sense with this feature set. If a user has permission to `Create` an app or service, shouldn't they then have permission to `Update` and probably `Delete` that app or service? There might be apps created by many users, and it shouldn't be required to edit the glob pattern to be able to say that that user can access the apps or services that (s)he has created.

 - If ownership by a user makes sense, then having a `/user/:user_id/{app,pkg}/:id` mirror of `/{app,pkg}/:id` might make sense as well. E.G. allowing `PUT /user/1234/app/UserName-AppName-nonce/service/start`. I'm kinda iffy on this suggestion, as the auth checker will have to check the same stuff anyway, so it won't boost performance, and the HTTP API is only meant to be used for creating the web- and perhaps future native-UIs. However, it does seem appropriate to add this feature to the CLI, IMO.

 - Ownership by a group is unnecessary as a group would define permission sets inherently.

I'm a little worried about the concept of this in general. It lays a lot of responsibility of the general sysadmin to understand the API. If the system for creating user permissions is too complicated, an admin will tend towards permissions that are less restrictive.

**Comment by dscottboggs** [comment]
My issue comes from this. For the current implementation, to limit a user to be able to Create any app/pkg, and to only be able to update/delete a subset of packages, the config file has to be updated like so:

##### *original*
```json
{
  "groups": [
    {
      "name": "Normal user",
      "id": 850,
      "permissions": [
        {
          "path pattern": "/app/*",
          "permissions": "Create"
        },{
          "path pattern": "/app/{app-id-one,app-id-two,app-id-three}/config/**",
          "permissions": "All"
        },{
          "path pattern": "/app/{app-id-one,app-id-two,app-id-three}/service/*",
          "permissions": "All"
        },
      ]
    }
  ]
}
```

If a user POSTed an app `app-id-four`, the config.json file would have to be changed to

```json
{
  "groups": [
    {
      "name": "Normal user",
      "id": 850,
      "permissions": [
        {
          "path pattern": "/app/*",
          "permissions": "Create"
        },{
          "path pattern": "/app/{app-id-one,app-id-two,app-id-three,app-id-four}/config/**",
          "permissions": "All"
        },{
          "path pattern": "/app/{app-id-one,app-id-two,app-id-three,app-id-four}/service/*",
          "permissions": "All"
        },
      ]
    }
  ]
}
```

Under my proposal, the config file could be more like:

```json
{
  "groups": [
    {
      "name": "Normal user",
      "id": 850,
      "permissions": [
        {
          "path pattern": "/app/**",
          "owned permissions": "All",
          "not-owned permissions": "None"
        },{
          "path pattern": "/app/*",
          "owned permissions": "All",
          "not-owned permissions": "Create"
        }
      ]
    }
  ]
}
```

And each app/pkg would have an `owner`(`s`) property on it that would either be a list of or an individual owner for each app/service.

**Comment by j8r** [comment]
> If a user has permission to Create an app or service, shouldn't they then have permission to Update and probably Delete that app or service?

Not necessarily, it should remain the admin's  decision

> There might be apps created by many users, and it shouldn't be required to edit the glob pattern to be able to say that that user can access the apps or services that (s)he has created.

Agree. In my opinion, to keep this simple, all permissions should stay only in groups. That's how some other APIs work too like Amazon's IAMs and HashiCorp Vault policies. An user may be the only member of its own group. A simple idea for is to allow the user All rights only on the apps ending by `*-owned-by-groupname`. Another option is to put application in groups too, but I'm afraid t will over complicate all of this.

> However, it does seem appropriate to add this feature to the CLI, IMO.

For now the CLI is only meant for the super user. This may change later, perhaps having a CLI client  of the API

> For the current implementation, to limit a user to be able to Create any app/pkg, and to only be able to update/delete a subset of packages, the config file has to be updated like 

IMO the API shouldn't automagically grant/remove rights behind the will of the Admin. Only this person, and other authorized apps//people have the right to do so.

**Comment by dscottboggs** [comment]
> Not necessarily, it should remain the admin's decision

I agree, which is why each group has an owned and not-owned permission-set.

> A simple idea for is to allow the user All rights only on the apps ending by *-owned-by-groupname. 

I don't like the idea of storing (and hence parsing) information in the unique ID, especially considering users may set their apps name. I get that you mean appending that value to what the user inputs, but it just *feels* like bad practice, you know?

> In my opinion, to keep this simple, all permissions should stay only in groups. That's how some other APIs work too like Amazon's IAMs and HashiCorp Vault policies. An user may be the only member of its own group.

Yes, you're right, now that I think about it, I think *group* ownership makes sense, but not user ownership. A group could have a (by default, empty) array of `"owned {apps,packages}"`, and then a permission set for the owned subjects and others.

The only other way I can see to effectively implement this is to create a new permission group for each application-user, automatically. Perhaps by having an `"inherited"` template property? That gets way over-complicated though, and having one group per user per app/pkg, and would create an exponentially growing number of groups, leading to performance issues down the line.

> IMO the API shouldn't automagically grant/remove rights behind the will of the Admin. Only this person, and other authorized apps//people have the right to do so.

I don't think the admin being able to set up a user with the ability to update and remove apps they've created is automagic or behind the will of the admin, it seems like an important convenience, and I don't see how it would reduce security in a significant way.

**Comment by j8r** [comment]
Another simple solution is to create a new directory, `/app/namespace/{app_name}`.
In the future, I'm planning to support other package sources so this will be consistent. To sum up, say an user, belonging to the group `default-user-group` want to install `dppm`:
- `/src/default-packages-source/dppm/pkg.con` will be parsed. The default [packages source](https://github.com/DFabric/packages-source) is called `default-packages-source`
- `/pkg/default-packages-source/dppm_2019-03-31` will be created.
- `/app/default-user-group/my-new-dppm` will be created

The group `default-user-group` has all rights on apps created on `/app/default-user-group`.

**Comment by dscottboggs** [comment]
I like this. A great way to do it.

**Comment by j8r** [comment]
What API call we'll have to modify the permissions of a given path? How can we prevent having duplicate paths?

I think it's better to have
```json
"mypath/patern/*/": {
  "permissions": []
}
```

It's a bit more user friendly, and we don't have to check for duplicates path paterns
That's a bit how AppArmor and HashiCorp Vault do.

**Comment by dscottboggs** [comment]
Sure, we can do it as a mapping instead. I just generally prefer to keep things in structs in Crystal -- as opposed to a struct and a mapping that is somewhere else, simply for organizational purposes. But I agree it is more user friendly.

As far as the API goes, I envisioned basic CRUD on a `/users/` and `/groups` base endpoint. Permissions would be verified the same as for other endpoints.

Does the namespace you suggested above correlate to the prefix in your CLI? We can work that into the API as a path or query parameter, then the API would look something like this...

```crystal
get "/dppm/api/app/:prefix/:app_name/config/:key" do |context|
  # find the app with prefix :prefix, named :app_name, and find config option :key
end
get "/dppm/api/app/:app_name/config/:key" do |context|
  # find the app with the default prefix named :app_name, and find config option :key
end
put "/dppm/api/app/:prefix/:app_name/config/:key" do |context|
  # find the app with prefix :prefix, named :app_name, and find config option :key
end
put "/dppm/api/app/:app_name/config/:key" do |context|
  # find the app with prefix :prefix, named :app_name, and find config option :key
end
# etc...
```

**Comment by j8r** [comment]
prefix is like `npm`'s: it's the base path from `/`, so it's `/srv/dppm/`. In you case, it's equal to `/dppm/api/`. Prefix means litteraly "everything before".

As proposed, we got `/:prefix/:app_path/:namespace/app_name`, that can correspond to `/dppm/api/``/app/``/default/``/my_app/`

**Comment by j8r** [comment]
`app_path` includes prefix, so it's `/srv/dppm/app` in the filesystem

**Comment by dscottboggs** [comment]
Oh, I see. Ok thanks for the clarification.

**Comment by j8r** [comment]
Also, using a `Hash`, except being cleaner, may also be more efficient – iterating on each element to find a value from a key compared to just finding a key.
I strongly think we should focus more of what's more convenient for the user than for us. Plus, the validation is easier.
