### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by dscottboggs** [DFabric/dppm-rest-api#15]
Since the beginning of the project, I have been using the convention of returning an JSON object which has at its top-level some meaningful keys which our client can look for (I.E. `{"errors": ..., "data": ...}`). The "errors" key is always present -- in the case of no errors it is an empty list. The reason for it being a list is so that we can express to the user (or the author of a client library) a more meaningful error, by allowing the server to note a list of errors rather than a single one. 

However, the built-in error handling solutions in Crystal (raising exceptions) and in Kemal (exceptions, `halt`) are ideally designed to stop the execution of the context upon an error, without going on. My [initial idea](https://github.com/DFabric/dppm-rest-api/pull/13) was to store a list of errors on `HTTP::Server::Context`, but after looking through the overrides Kemal offers on `Context`, I thought of [this solution](https://github.com/DFabric/dppm-rest-api/pull/14).

Now that I think about it though, neither solution works at all. The result would look something like...
```json
{
  "data": { "some": "data" }
}
{
  "errors": ["an error", "Not Found"]
}
```
... which isn't even valid JSON.

Maybe if we check if `context.response` is empty (hasn't yet been written to) before writing to it in the [error handler](https://github.com/DFabric/dppm-rest-api/blob/eecbaf30649ae57fd14daf1ef73633fa4100a693/src/middlewares/error_handlers.cr). Idk, that still doesn't solve the issue of what to do inside `Actions.throw_error` and the `deny_access!` macro.

**Comment by j8r** [comment]
Agree, either `data` or `errors` but not both at the same time.
We should avoid monkey patching here, I think we can do without.
I may have a solution, let me try something.

**Comment by dscottboggs** [comment]
>  either data or errors but not both at the same time.

That was one of the primary points of this -- to be able to send errors as well as data. I just had an idea -- what if we sent the errors through headers instead of the body, and successful information through the body? Headers already implement the mapping of string to Array(String) that I wanted for errors. I've seen this pattern in Rails and other frameworks. A hash is available to set request headers like:

```crystal
flash[:error] = "something"
# or
flash.error "something"
# Since messages can be a list as opposed to simply set we can also
flash[:error] << "something"
# or
flash[:error].push  "something"
# However, all of these would simply do
context.response.headers.add "error", "something"
```
client side we could do something like

```js
function showErrors(headers) {
  if( headers ) {
    let errors = headers.get('error')
    if (errors)
      errors.split(',').forEach(showError)
  }
}
authFetch('/app/something').then( response => {
  showErrors(response.headers)
  ...
)
```
As a general idea, I was planning to implement a `showError()` function which displays a [notification](https://bulma.io/documentation/elements/notification/) to the user, with the intent to be able to show multiple per-request.

Anyway, I like the idea of sending the data and errors through separate channels. Let me know what you think. :slightly_smiling_face:

**Comment by j8r** [comment]
What value in `data` will be returned if the server encountered an error?
I'am afraid using headers will be too limited.
After looking at https://jsonapi.org/examples/#error-objects, we could take some ideas: `errors` can be a list of JSON objects.
To represent this in Crystal, we can also use a self-recursive class instead of an Array.

**Comment by dscottboggs** [comment]
Yes, I like that. However, what about the case where a user makes a batch request during which some cases succeed and some fail? Implementing that in kemal, with exception handlers as well, is a difficult, if not impossible question.

**Comment by j8r** [comment]
By batch request, you mean several operations in one single request, is it possible now?
How the batch can be made will influence what will be the result returned.
If the batch is a list of objects, a list of objects will be returned too, I guess.

**Comment by dscottboggs** [comment]
The only example currently in the API under which a batch request would be processed is the user API. However, it seems wise to allow for this circumstance in other cases in the future, especially since there's already one case where that can happen.

**Comment by j8r** [comment]
In short, the user set `data`, which is either a list of json objects or a json object, like in [jsonapi](https://jsonapi.org/format/#document-top-level), and sends its request.
Then, accordingly, the server may return a `errors` list or, `data` a list or object.

Does it looks correct to you?

**Comment by dscottboggs** [comment]
> The members data and errors MUST NOT coexist in the same document.

Why not? It seems sensible to me to be able to express both an error and success. But I'm not going to argue a standard, especially when following the standard means less work for me :smile:

**Comment by j8r** [comment]
That's a binary operation: either the request has succeeded and returns a 200 status code, or failed with a status code of 4xx or 5xx like 403 or 502.
You can put information in `errors`, so no need of `data`.

**Comment by dscottboggs** [comment]
So lets say that we have groups 1 through 5, and a user which is a member of groups 1-3. What happens if that user requests to be added to groups 4 and 6? Or to be removed from groups 2 and 10? How would we express the failure for the nonexistent group and the success of adding the user to or removing them from the group that does exist?

**Comment by j8r** [comment]
One request is sent per operation. It's possible to keep the same connection for several requests, according to HTTP/1.1:
- request to be add user to group 1 => OK/KO
- request to remove user to group 5 => OK/KO
etc...

**Comment by dscottboggs** [comment]
So basically the ability to do batch processing needs removed in the cases where it exists and not implemented in the places where it's planned.

**Comment by j8r** [comment]
It's fine to not having it. We have time to think about it, if it will become problem, one day. Even huge cloud providers like Amazon don't do this AFAIK.

**Comment by j8r** [comment]
Not really solved – how to do a list of errors in response of a single request, like [in this example](https://jsonapi.org/examples/#error-objects-multiple-errors)

**Comment by dscottboggs** [comment]
Right. Sorry. How about if there was an `Actions.push(key : String, value) ` and `Actions.pop(key : String)`, like in my second example, but as methods on the `Actions` module alongside `deny_access!`, et al?

**Comment by j8r** [comment]
Simple example in our case: `POST /app/default/new_app`.
Error trace:
- `500 Access forbidden: /root`
- `500 Failed to build 'gitea'`
- `503 Failed to add 'new_app'`

**Comment by j8r** [comment]
I don't think lists are necessary.

Sorry for the self-promotion, we can use https://github.com/j8r/error.cr 😅 
We can therefore create a custom error, with this advantages:
- error trace thanks to ivar self-recursion (like normal Exceptions)
- being able to construct a JSON error for the client **and** log error traces with file, line, methods and objects for the server.
- performant, minimal stack unwinding

**Comment by dscottboggs** [comment]
so in the handler, I'd do like

```crystal
push "error", {status: 500, message: "Access denied to /root"}
push "error", {status: 500, message: "Failed to build 'gitea'"}
push "error", {status: 503, message: "Failed to add 'new_app'"}
```
I don't really see the point in status codes if they're not being used specifically for the status of the request, so a more simple implementation would be like
```crystal
push "error", "Access denied to /root"
push "error", "Failed to build 'gitea'"
push "error", "Failed to add 'new_app'"
```
Then in the error handler
```crystal
JSON.build context.response do |builder|
  builder.object do
    builder.field "errors" do
      builder.array do
        builder.string {{status_code}}.description || "{{status_code.id}}".capitalize
        while message = pop? "error"
          builder.string message
        end
      end
    end
  end
end
```

If you don't want to use lists, we could use Kemal's `Context#set`/`#get` methods to store the error message to relay to the error handler.

Error.cr won't work with Kemal because Kemal's actions are captured blocks, which can't be returned from :slightly_frowning_face:

**Comment by j8r** [comment]
That's not really I don't want list, but we really should have a stack trace too, and of course build a JSON error too.
The application will become bigger and bigger, it will simplify our life a lot for debugging.

I think it's possible with Kemal?

**Comment by dscottboggs** [comment]
I think that logging errors makes sense, as well as other events, and that those logs should include the location in the source code where the problem is. That makes sense. And Kemal has a logger that is configurable based on the Kemal environment. I think that's a separate issue, though, and shouldn't necessarily be intertwined with error responses to the user.

**Comment by j8r** [comment]
Right. Remains to find a solution that doesn't monkey patch stdlib's `HTTP::Server::Context`, ideally...

**Comment by dscottboggs** [comment]
I was going to suggest that we put those methods on the actions module, but that would need to be associated per-context anyway. I would argue that the entire purpose of `HTTP::Server::Context` is to store data that is relevant to the request context, for passing between middlewares, like [Kemal's reopening of Context](https://github.com/kemalcr/kemal/blob/c646aad482acd53920f9844e0fee30d544798bfb/src/kemal/ext/context.cr#L49). Is there any place else which would be appropriate?

In general, what is the argument against reopening classes? I don't see the harm.

**Comment by j8r** [comment]
If everybody patch the stdlib, it can quickly becomes a mess. Harder to find docs for this non-standard methods.
I think we should ask in Gitter and in the Kemal channel first if there are better ways to do this.
It would be interesting to know how other framerworks do, too.

**Comment by j8r** [comment]
What will be the cases when multiple errors have to be catched **inside** dppm-rest-api?
As now, we can take the `Exception` and have the `@cause` `Exception` inside it.
