### ISSUE TITLE
Running specs out of the box

### ISSUE THREAD

**Issue by j8r** [DFabric/dppm-rest-api#17]
- running `crystal spec` hangs indefinitely. Ideally, it should work out of the box.
- a hash in `spec/permissions.json` changes, this is a bit annoying. It may be linked to the upper command, so adding to `.gitignore` isn't a proper solution.

**Comment by dscottboggs** [comment]
The reason `crystal spec` hangs is that you must run it with `$KEMAL_ENV` set to "test". This is inherent to the kemal-spec library.

> a hash in spec/permissions.json changes, this is a bit annoying

I agree, I've just been doing `git checkout --` on it before committing other stuff but it's definitely less than ideal. I'll figure out a way to get the specs to restore it to its original state.

**Comment by j8r** [comment]
For `KEMAL_ENV`, we can do like in [Kemal specs](https://github.com/kemalcr/kemal/blob/master/spec/spec_helper.cr#L79):
```cr
Spec.before_each do
  config = Kemal.config
  config.env = "development"
  config.logging = false
end
```
