### ISSUE TITLE
Security: Validations

### ISSUE THREAD

**Issue by dscottboggs** [DFabric/dppm-rest-api#23]
# Validations
This issue is here to note the necessary steps we need to take to validate any and all received data from the API before passing it through to the library. A high-level discussion of implementation may be appropriate, but details should be worked out in a PR that will later be linked to this issue. This is an important security step (especially since many parameters translate directly to file-paths!) and we should be careful to be well-organized and methodical in our implementation of this feature.

## Types of validations

- [ ] Reject parameters containing characters that aren't relevant to the value expected to be received.
- [ ] Reject parameters that do not fit within an expected range of values. For example, when building a package, we could check that the package id is one of the known source names.
- [ ] Size of received parameters
- [ ] Path traversal issues (potentially covered by the first validation, depending on the parameter and how it is used)

### Path parameters
_TODO_
### Query Parameters
_TODO_

**Feel free to edit this summary as needed to update to-do lists, documentation, etc.**

**Comment by dscottboggs** [comment]
Implementation-wise I was thinking we could define a simple `spec`-like DSL for validations, something like

```crystal
module Pkg
  relative_get "/:id/build" do |context|
    expect(:path, :id).to_be_alphanumeric
      .and.to_be_in list_of_sources
  end
end
```

This would obviously preclude the client from using the `pkg-name_pkg-ver` format, but that's a limitation I can accept. The DSL could be implemented simply by using a module where each method is chainable, returned by a global `expect` function.

**Comment by j8r** [comment]
`DppmRestApi` should only validate new params introduced by it, not those passed to the library, that are already validated.

**Comment by dscottboggs** [comment]
That makes this a much smaller project.

**Comment by j8r** [comment]
Usually methods like `build`, `delete` etc validates first the arguments, then yield a block for confirmation, then perform changes on disk.
You may have a better idea how to do it? This approach has the advantage to only have one method instead of having methods like `build_validation` then `build`. This will be more error prone and cumbersome.

This type of logic can be used:
```cr
pkg = prefix.new_pkg package_name, version: context.params.query["version"]?
init_done = false
begin
  pkg.build confirmation: false { init_done = true }
rescue e
  raise InternalServerError.new context, cause: e if init_done
  raise BadRequest.new context, cause: e
end
```

**Comment by dscottboggs** [comment]
Validations are performed and to be performed by the underlying library.
