### ISSUE TITLE
User/Group Modification REST endpoints

### ISSUE THREAD

**Issue by dscottboggs** [DFabric/dppm-rest-api#9]
To allow editing user permissions from the web UI or other end-user application.

- [ ] _POST_ `/user` 
  **JSON body**: user's name and group membership.
  **Accepted Keys**: `[ "name", "groups" ]`
  **Returns**: API key.
- [ ] _PUT_ `/users`
  **JSON body**: selectors and modifiers for users.
  **Accepted Keys**: `[ "match_name", "match_groups", "api_key", "new_name", "add_groups", "remove_groups" ]`
- [ ] _PUT_ `/user` edit the current user
  **JSON Body**: modifiers for the user
  **Accepted Keys**: `[ "new_name", "add_groups", "remove_groups" ]`
- [ ] _DELETE_ `/users`
  **JSON body**: of selectors for users
  **Accepted Keys**: `[ "match_name", "match_groups", "api_key" ]`
- [ ] _GET_ `/user`
  **Returns**: information about the currently signed in user
- [ ] _GET_ `/users`
  **JSON body**: selectors
  **Returns**: JSON-formatted list of user information
- [ ] _PUT_ `/user/rekey`
  **Returns**: A new API key for the currently signed-in user.
- [ ] _PUT_ `/users/rekey`
  **JSON body**: selectors
  **Returns**: the new user's API key.
  **Error**: if more than one user was selected.
- [ ] _POST_ `/groups`
  **JSON body**: the group
- [ ] _PUT_ `/groups/:id/route`
  **JSON body**: a new route to add to the group
- [ ] _PUT_ `/groups/:id/param`
  **JSON body**: a mapping of a path to a list of globs to add to those available on that path
- [ ] _DELETE_ `/groups/:id/param`
  **JSON body**: a group mapping a path to a list of globs to remove
- [ ] _DELETE_ `/groups/:id`
  Deletes the group

**Comment by j8r** [comment]
Looks good
I suggest to have a singular `user` to get information for the actual user in use (group, permissions, etc), and plural variants, `/users` and `/groups` for general users/groups operations.
What about `/login`? Maybe having `/user/login`?

**Comment by dscottboggs** [comment]
Sure, there's an option in `KemalJWTAuth` to change the default login path, so we can set that as well as a part of this.

**Comment by dscottboggs** [comment]
Updated

I like that a lot better
